<p style="font-size:30px; font-weight:bold;">Manuplating tensors(Tensor operations)</p>

Tesnor opertion include: arihtmetic operations and matrix opertaions

In [1]:

import torch
print("PyTorch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())
print("CUDA version (PyTorch):", torch.version.cuda)
print("GPU:", torch.cuda.get_device_name(0))


PyTorch version: 2.5.1
CUDA available: True
CUDA version (PyTorch): 11.8
GPU: NVIDIA GeForce RTX 4060 Laptop GPU


In [2]:
tensor = torch.tensor([1,2,3])
print(f"Addition of tensors {tensor + 10}")
print(f"Subtraction of tensors {tensor -10}")
print(f"Multiplication of tensors {tensor*10}")
print(f"Division of tensors {tensor/10}")

Addition of tensors tensor([11, 12, 13])
Subtraction of tensors tensor([-9, -8, -7])
Multiplication of tensors tensor([10, 20, 30])
Division of tensors tensor([0.1000, 0.2000, 0.3000])


<p style="font-size:30px; font-weight:bold;">Matrix Multiplication in pytorch</p>

1.Element wise multiplication 

2.Matrix wise multiplication i.e Dot prodcut

In [3]:
#1Element wise multiplication
print(tensor,"*",tensor)
print(f"Equals : {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals : tensor([1, 4, 9])


In [4]:
#Matrix multiplication
torch.matmul(tensor,tensor)


tensor(14)

In [5]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: total: 0 ns
Wall time: 7.73 ms


In [6]:
%%time
torch.matmul(tensor,tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

### Finding min,max,mean,sum etc.

In [7]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [8]:
torch.min(x),x.min()

(tensor(0), tensor(0))

In [9]:
#torch.mean(x)

In [10]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [11]:
torch.sum(x),x.sum()

(tensor(450), tensor(450))

### Finding postional min and max value


In [12]:
x.argmin() #returns the index at which the minimum value is present

tensor(0)

In [13]:
x.argmax() #returns the index at which the maximum value is present

tensor(9)

## Reshaping, stacking, squeeezing and unsquezzing tensors      
* Squeezing = removes all '1' dimension from a tensor
* unsqueeze = add a '1' dimension to a tensor
* permute = return a view of the input with dimensions permuted(swapped) in a certian way

In [14]:
import torch
x = torch.arange(1.,10.)
x ,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [15]:
#add an extra dimension
x_reshaped = x.reshape(1,9)
x,x_reshaped

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]))

In [16]:
#change the view
z = x.view(1,9)
z ,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [17]:
#changing z changes x
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [18]:
#Stack tensors on top of each other
x_stack_1 = torch.stack([x,x,x],dim=1)

x_stack_0 = torch.stack([x,x,x],dim=0)
x_stack_1,x_stack_0

(tensor([[5., 5., 5.],
         [2., 2., 2.],
         [3., 3., 3.],
         [4., 4., 4.],
         [5., 5., 5.],
         [6., 6., 6.],
         [7., 7., 7.],
         [8., 8., 8.],
         [9., 9., 9.]]),
 tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]))

In [19]:
x = torch.zeros(2,1,2,1,2)
print(x.size(),"\n")

y = torch.squeeze(x)
print(y.size(),"\n")

y = torch.squeeze(x,0)
print(y.size(),"\n")

y = torch.squeeze(x,1)
y.size()


torch.Size([2, 1, 2, 1, 2]) 

torch.Size([2, 2, 2]) 

torch.Size([2, 1, 2, 1, 2]) 



torch.Size([2, 2, 1, 2])

In [20]:
#torch.squeeze() remove all single dimensions from a target tensor
print(f"previous tensor:{x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

#remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor:{x_squeezed}")
print(f"New tensor shape:{x_squeezed.shape}")

previous tensor:tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor:tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New tensor shape:torch.Size([9])


In [21]:
#torch.unsqueeze() adds a single dimension to a target tension at a particular dimension (dim)
print(f"previous tensor{x_squeezed}")
print(f"previous shape{x_squeezed.shape}")
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"New unsqueezed : {x_unsqueezed}")
print(f"New shape : {x_unsqueezed.shape}")

previous tensortensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
previous shapetorch.Size([9])
New unsqueezed : tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape : torch.Size([1, 9])


In [22]:
#torch.permute - rearrnages the dimension of a target in a specified oreder
#torch.permute(X,(dim1,dim2, ..... ,dim n))

x = torch.randn(5,6,7)
print(f"before permute : {x.size()}")
x_permuted  = torch.permute(x,(2,1,0))
print(f"After permute : {x_permuted.size()}")
#note permute is a view of the tensor it changes the dim of the tensor but not its internal values

before permute : torch.Size([5, 6, 7])
After permute : torch.Size([7, 6, 5])


In [23]:
x[0,0,0] =  6220
x[0,0,0],x_permuted[0,0,0]




(tensor(6220.), tensor(6220.))

## Indexing is similar to numpy in pytorch
#### arange(start,end - 1, step)


In [24]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
print(f"x : {x}\nx's shape : {x.shape}")


x : tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
x's shape : torch.Size([1, 3, 3])


In [27]:
print(f"(0) :  {x[0]}")
print(f"\n(0,0) :  {x[0,0]}")
print(f"\n(0,0,0) :  {x[0,0,0]}")
print(f"all first dim , all second dim , first third dim {x[:,:,0]}")

(0) :  tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

(0,0) :  tensor([1, 2, 3])

(0,0,0) :  1
all first dim , all second dim , first third dim tensor([[1, 4, 7]])


In [28]:
print(f"all first dim , second second dim,all third dim{x[:,1,:]}")

all first dim , second second dim,all third dimtensor([[4, 5, 6]])


In [29]:
import numpy as np
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
print(f"\n{array}\n{tensor}")


[1. 2. 3. 4. 5. 6. 7.]
tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)


## Float32 is pytorch's default datatype

In [1]:
#Numpy to array to tensor
import torch
import numpy as np
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) #warning : wehn converting from numpy -> pytorch reflecs numpy's default datatype of float64 unless specified otherwise
array , tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [2]:
# change the value of array , waht will this do to the 'tensor'?
array = array + 1
array , tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [3]:
torch.arange(1.0,8.0).dtype

torch.float32

In [4]:
#Tensor to numpy array
tensor = torch.ones(7)
numpy_tensor =  tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [5]:
#change the tensor ,What happens to numpy_tensor?
tensor =  tensor + 1
tensor, numpy_tensor  

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))