## Reporducibility trying to take out random from random


#### In short how a neural network learns:
#### start with random numbers --> perform tensor opertaions --> 
#### update random numbers to try and make them better represntation of the data  --> reapeat

In [1]:
import torch
import numpy as np 

In [2]:
torch.rand(3,3)

tensor([[0.0872, 0.0183, 0.3667],
        [0.2645, 0.5560, 0.3830],
        [0.9527, 0.6921, 0.0627]])

#### To reduce the randomnees in neural networks and torch we use seeds
#### It adds flavour to randomness

In [5]:
rand_tensor_1 = torch.rand(9,9)
rand_tensor_2 = torch.rand(9,9)
print(rand_tensor_1)
print(rand_tensor_2)
print(rand_tensor_2 == rand_tensor_1)


tensor([[0.4219, 0.8532, 0.1018, 0.4534, 0.5484, 0.0403, 0.2175, 0.7729, 0.8914],
        [0.7238, 0.3494, 0.7760, 0.4785, 0.5702, 0.4313, 0.4704, 0.3240, 0.1600],
        [0.5742, 0.0315, 0.4438, 0.6483, 0.7996, 0.5035, 0.1603, 0.2753, 0.9020],
        [0.9642, 0.5796, 0.8063, 0.6921, 0.0592, 0.6434, 0.7470, 0.2153, 0.7538],
        [0.6492, 0.7765, 0.9921, 0.6426, 0.2327, 0.0364, 0.3049, 0.2416, 0.9753],
        [0.8707, 0.1303, 0.5946, 0.9886, 0.0629, 0.1889, 0.4551, 0.5228, 0.8964],
        [0.5951, 0.8706, 0.6362, 0.3900, 0.0054, 0.1639, 0.8960, 0.8200, 0.7665],
        [0.5759, 0.4051, 0.5455, 0.9868, 0.1351, 0.5956, 0.5560, 0.8335, 0.7141],
        [0.5171, 0.6184, 0.3642, 0.1177, 0.6468, 0.4117, 0.2543, 0.3747, 0.8804]])
tensor([[0.7467, 0.2529, 0.4150, 0.1682, 0.5555, 0.0186, 0.8151, 0.9512, 0.1951],
        [0.3762, 0.3087, 0.7857, 0.7027, 0.9046, 0.3069, 0.5564, 0.4591, 0.4719],
        [0.4118, 0.4586, 0.1998, 0.6562, 0.2938, 0.4351, 0.8204, 0.8496, 0.5621],
        [0.9421

## making random but reproduccable tensors 
* Note : use torch.manual_seed everytime while creating a tensor to create same random tensors

In [ ]:
import torch
seed = 67

torch.manual_seed(seed)#for  random tensor 3
random_tensor_3 = torch.rand(9,9)
torch.manual_seed(seed)# for random tensor 4 
random_tensor_4 = torch.rand(9,9)

print(random_tensor_3)
print(random_tensor_4)
print(random_tensor_3 == random_tensor_4)


tensor([[0.7380, 0.3646, 0.8673, 0.5464, 0.5885, 0.9785, 0.8875, 0.9903, 0.3595],
        [0.3245, 0.8871, 0.9991, 0.5664, 0.5706, 0.7217, 0.2157, 0.0415, 0.2903],
        [0.0052, 0.8127, 0.2556, 0.6512, 0.5186, 0.6332, 0.5303, 0.2814, 0.6596],
        [0.6492, 0.0865, 0.3869, 0.6819, 0.2390, 0.8542, 0.7344, 0.8452, 0.6987],
        [0.8547, 0.6188, 0.5371, 0.4756, 0.0563, 0.4369, 0.4823, 0.3503, 0.8054],
        [0.7139, 0.5925, 0.5760, 0.6001, 0.7417, 0.0029, 0.3852, 0.3063, 0.7652],
        [0.3698, 0.8447, 0.0767, 0.4960, 0.0928, 0.3855, 0.9764, 0.4763, 0.8621],
        [0.0743, 0.4259, 0.6866, 0.1963, 0.8095, 0.4213, 0.9940, 0.5490, 0.7117],
        [0.9492, 0.8565, 0.3673, 0.9702, 0.7095, 0.0099, 0.8118, 0.5898, 0.2141]])
tensor([[0.7380, 0.3646, 0.8673, 0.5464, 0.5885, 0.9785, 0.8875, 0.9903, 0.3595],
        [0.3245, 0.8871, 0.9991, 0.5664, 0.5706, 0.7217, 0.2157, 0.0415, 0.2903],
        [0.0052, 0.8127, 0.2556, 0.6512, 0.5186, 0.6332, 0.5303, 0.2814, 0.6596],
        [0.6492

Resources for reproducability 
* https://docs.pytorch.org/docs/stable/notes/randomness.html

### How to run pytorch on cuda cores
1. Use kaggle or google colab (cloud)
2. use your own gpu (local)

In [10]:
! nvidia-smi

Wed Dec 31 23:41:07 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 581.80                 Driver Version: 581.80         CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4060 ...  WDDM  |   00000000:01:00.0  On |                  N/A |
| N/A   40C    P8              3W /  140W |     686MiB /   8188MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

#### Command to check if pytorch can access the gpu

In [4]:
import torch
torch.cuda.is_available()


True

In [6]:
#Setup device agonstic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [7]:
#count the number of devies 
torch.cuda.device_count()

1

In [8]:
#using the cpu
tensor = torch.rand(9,9)
print(tensor,tensor.device)

tensor([[0.5013, 0.4452, 0.7869, 0.9637, 0.2582, 0.3568, 0.7991, 0.2599, 0.8964],
        [0.2529, 0.5564, 0.6611, 0.6101, 0.4567, 0.1638, 0.3477, 0.2230, 0.9606],
        [0.4565, 0.8128, 0.8777, 0.5204, 0.3341, 0.8123, 0.7479, 0.7628, 0.0709],
        [0.0459, 0.1621, 0.6009, 0.8316, 0.1237, 0.9376, 0.2486, 0.4303, 0.8859],
        [0.1144, 0.6289, 0.6145, 0.6791, 0.6231, 0.0577, 0.9987, 0.7342, 0.0186],
        [0.9179, 0.3615, 0.1105, 0.6583, 0.8099, 0.7776, 0.0289, 0.5894, 0.4252],
        [0.4244, 0.6206, 0.4316, 0.9052, 0.1064, 0.0558, 0.3933, 0.5089, 0.9718],
        [0.9509, 0.5328, 0.9505, 0.4434, 0.5715, 0.0176, 0.6744, 0.4778, 0.1816],
        [0.6058, 0.5975, 0.6718, 0.4576, 0.6340, 0.8367, 0.4168, 0.5071, 0.4863]]) cpu


In [9]:
#Moving tenosr to gpu
tensor_gpu = tensor.to(device)
tensor_gpu

tensor([[0.5013, 0.4452, 0.7869, 0.9637, 0.2582, 0.3568, 0.7991, 0.2599, 0.8964],
        [0.2529, 0.5564, 0.6611, 0.6101, 0.4567, 0.1638, 0.3477, 0.2230, 0.9606],
        [0.4565, 0.8128, 0.8777, 0.5204, 0.3341, 0.8123, 0.7479, 0.7628, 0.0709],
        [0.0459, 0.1621, 0.6009, 0.8316, 0.1237, 0.9376, 0.2486, 0.4303, 0.8859],
        [0.1144, 0.6289, 0.6145, 0.6791, 0.6231, 0.0577, 0.9987, 0.7342, 0.0186],
        [0.9179, 0.3615, 0.1105, 0.6583, 0.8099, 0.7776, 0.0289, 0.5894, 0.4252],
        [0.4244, 0.6206, 0.4316, 0.9052, 0.1064, 0.0558, 0.3933, 0.5089, 0.9718],
        [0.9509, 0.5328, 0.9505, 0.4434, 0.5715, 0.0176, 0.6744, 0.4778, 0.1816],
        [0.6058, 0.5975, 0.6718, 0.4576, 0.6340, 0.8367, 0.4168, 0.5071, 0.4863]],
       device='cuda:0')

In [10]:
#if tensor is on gpu you cannot transform it into numpy
tensor_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
# fixing the error by transfering the tensor to cpu and then converting to numpy 
tensor_cpu = tensor_gpu.cpu().numpy()
tensor_cpu

array([[0.5012764 , 0.445198  , 0.7868895 , 0.9636854 , 0.25817955,
        0.35682243, 0.7991078 , 0.2599247 , 0.8963651 ],
       [0.25293016, 0.5564109 , 0.661114  , 0.61014855, 0.45667344,
        0.16382486, 0.34767318, 0.2230081 , 0.9605534 ],
       [0.45645916, 0.81284744, 0.8776559 , 0.5203514 , 0.33408427,
        0.81226206, 0.747877  , 0.7628323 , 0.07090628],
       [0.04587728, 0.16206032, 0.6009148 , 0.83158416, 0.12371075,
        0.9376492 , 0.24862707, 0.43025982, 0.8859216 ],
       [0.11437005, 0.62891513, 0.61446077, 0.67907685, 0.62305385,
        0.05766708, 0.99872965, 0.73415405, 0.01859754],
       [0.9179293 , 0.36149037, 0.11053413, 0.65827197, 0.8098705 ,
        0.7776318 , 0.02891898, 0.5894025 , 0.42519772],
       [0.42441332, 0.62057024, 0.4316371 , 0.90518534, 0.10637182,
        0.05577052, 0.393292  , 0.5088766 , 0.97182983],
       [0.9508641 , 0.53284013, 0.9504574 , 0.4434427 , 0.5715222 ,
        0.01755005, 0.6743517 , 0.4777729 , 0.18163896],


In [14]:
# the tensor on the gpu remains unchanged when we transfer it back to the cpu
tensor_gpu

tensor([[0.5013, 0.4452, 0.7869, 0.9637, 0.2582, 0.3568, 0.7991, 0.2599, 0.8964],
        [0.2529, 0.5564, 0.6611, 0.6101, 0.4567, 0.1638, 0.3477, 0.2230, 0.9606],
        [0.4565, 0.8128, 0.8777, 0.5204, 0.3341, 0.8123, 0.7479, 0.7628, 0.0709],
        [0.0459, 0.1621, 0.6009, 0.8316, 0.1237, 0.9376, 0.2486, 0.4303, 0.8859],
        [0.1144, 0.6289, 0.6145, 0.6791, 0.6231, 0.0577, 0.9987, 0.7342, 0.0186],
        [0.9179, 0.3615, 0.1105, 0.6583, 0.8099, 0.7776, 0.0289, 0.5894, 0.4252],
        [0.4244, 0.6206, 0.4316, 0.9052, 0.1064, 0.0558, 0.3933, 0.5089, 0.9718],
        [0.9509, 0.5328, 0.9505, 0.4434, 0.5715, 0.0176, 0.6744, 0.4778, 0.1816],
        [0.6058, 0.5975, 0.6718, 0.4576, 0.6340, 0.8367, 0.4168, 0.5071, 0.4863]],
       device='cuda:0')

# Documnetation reading is important
#### resources to practice pytorch
* https://docs.pytorch.org/tutorials/beginner/pytorch_with_examples.html
